import type { Ability } from '../types'

export const ABILITIES: Record<string, Ability> = {
  submit_837p: {
    id: 'submit_837p',
    name: '837P Claim',
    faction: 'provider',
    cooldown: 800,
    damage: 20,
    range: 200,
    projectileSpeed: 400,
    effect: 'Standard professional claim shot.',
    teaches: 'The basic professional claim — what 90% of revenue rides on.',
  },
  submit_837i: {
    id: 'submit_837i',
    name: '837I Claim',
    faction: 'provider',
    cooldown: 1000,
    damage: 28,
    range: 180,
    projectileSpeed: 350,
    effect: 'Facility claim — slower but heavier.',
    teaches: 'Institutional vs. professional split — same visit, two claims.',
  },
  eligibility_270: {
    id: 'eligibility_270',
    name: 'Eligibility (270)',
    faction: 'provider',
    cooldown: 600,
    damage: 12,
    range: 250,
    projectileSpeed: 500,
    blocksFactions: ['patient', 'employer'],
    effect: 'Fast check. Strong vs patient/employer denials.',
    teaches: 'Eligibility is cheap; omitting it is expensive later.',
  },
  prior_auth_278: {
    id: 'prior_auth_278',
    name: 'Prior Auth (278)',
    faction: 'payer',
    cooldown: 1200,
    damage: 18,
    range: 220,
    projectileSpeed: 350,
    blocksFactions: ['payer'],
    effect: 'Authorization shot. Blocks precert denials.',
    teaches: 'The 278 transaction is the auth — most providers still fax.',
  },
  appeal_letter: {
    id: 'appeal_letter',
    name: 'Appeal Letter',
    faction: 'provider',
    cooldown: 2000,
    damage: 45,
    range: 160,
    projectileSpeed: 280,
    effect: 'Heavy hit — slow cooldown.',
    teaches: 'Appeals work — but the time cost is the real story.',
  },
  cdi_query: {
    id: 'cdi_query',
    name: 'CDI Query',
    faction: 'provider',
    cooldown: 900,
    damage: 22,
    range: 200,
    projectileSpeed: 380,
    blocksFactions: ['provider'],
    effect: 'Documentation tightening. Strong vs provider-cause denials.',
    teaches: 'CDI is upstream of every medical-necessity denial.',
  },
  claim_scrubber: {
    id: 'claim_scrubber',
    name: 'Claim Scrubber',
    faction: 'vendor',
    cooldown: 700,
    damage: 18,
    range: 240,
    projectileSpeed: 450,
    blocksFactions: ['vendor'],
    effect: 'Fast front-end clean. Strong vs vendor errors.',
    teaches: 'Front-end edits are 10x cheaper than back-end appeals.',
  },
  cob_check: {
    id: 'cob_check',
    name: 'COB Check',
    faction: 'employer',
    cooldown: 1000,
    damage: 16,
    range: 200,
    projectileSpeed: 380,
    blocksFactions: ['employer'],
    effect: 'Coordination of benefits. Blocks OA-23.',
    teaches: 'COB confusion is a Top-3 denial reason.',
  },
  medical_policy: {
    id: 'medical_policy',
    name: 'Policy Lookup',
    faction: 'payer',
    cooldown: 1100,
    damage: 20,
    range: 220,
    projectileSpeed: 360,
    blocksFactions: ['payer'],
    effect: 'Reveal coverage rules.',
    teaches: 'Payer policies are public — most denials are predictable.',
  },
  cost_estimate: {
    id: 'cost_estimate',
    name: 'Cost Estimate',
    faction: 'patient',
    cooldown: 900,
    damage: 14,
    range: 200,
    projectileSpeed: 400,
    blocksFactions: ['patient'],
    reputationDelta: 2,
    effect: 'Set patient expectations. +rep.',
    teaches: 'Same procedure, same plan, different deductible = different bill.',
  },
  aggressive_collections: {
    id: 'aggressive_collections',
    name: 'Collections',
    faction: 'provider',
    cooldown: 600,
    damage: 35,
    range: 180,
    projectileSpeed: 500,
    shadow: true,
    reputationDelta: -8,
    cashDelta: 10,
    effect: 'Heavy damage but costs reputation.',
    teaches: 'The provider was the bad guy this round.',
  },
  upcode: {
    id: 'upcode',
    name: 'Upcode',
    faction: 'provider',
    cooldown: 500,
    damage: 30,
    range: 200,
    projectileSpeed: 450,
    shadow: true,
    auditDelta: 8,
    cashDelta: 8,
    effect: 'Higher reimbursement. +audit risk.',
    teaches: 'This is fraud-adjacent. The boss remembers.',
  },
}

export const ABILITY_LIST = Object.values(ABILITIES)
