import type { Tool } from '../types'

export const TOOLS: Record<string, Tool> = {
  submit_837p: {
    id: 'submit_837p',
    name: '837P Claim',
    faction: 'provider',
    damage: 20,
    accuracy: 90,
    turnCost: 1,
    effectiveFactions: [],
    effect: 'Submit a professional claim.',
    teaches: 'The basic professional claim — what 90% of revenue rides on.',
  },
  submit_837i: {
    id: 'submit_837i',
    name: '837I Claim',
    faction: 'provider',
    damage: 28,
    accuracy: 85,
    turnCost: 1,
    effectiveFactions: [],
    effect: 'Submit an institutional claim. Heavier but slower.',
    teaches: 'Institutional vs. professional split — same visit, two claims.',
  },
  eligibility_270: {
    id: 'eligibility_270',
    name: 'Eligibility Check',
    faction: 'provider',
    damage: 12,
    accuracy: 95,
    turnCost: 1,
    effectiveFactions: ['patient', 'employer'],
    effect: 'Verify coverage before billing. Strong vs patient/employer issues.',
    teaches: 'Eligibility is cheap; omitting it is expensive later.',
  },
  prior_auth_278: {
    id: 'prior_auth_278',
    name: 'Prior Auth (278)',
    faction: 'payer',
    damage: 18,
    accuracy: 80,
    turnCost: 1,
    effectiveFactions: ['payer'],
    effect: 'Get authorization on file. Prevents precert denials.',
    teaches: 'The 278 transaction is the auth — most providers still fax.',
  },
  appeal_letter: {
    id: 'appeal_letter',
    name: 'Appeal Letter',
    faction: 'provider',
    damage: 40,
    accuracy: 70,
    turnCost: 2,
    effectiveFactions: [],
    effect: 'Heavy damage but costs 2 turns and lower accuracy.',
    teaches: 'Appeals work — but the time cost is the real story.',
  },
  cdi_query: {
    id: 'cdi_query',
    name: 'CDI Query',
    faction: 'provider',
    damage: 22,
    accuracy: 85,
    turnCost: 1,
    effectiveFactions: ['provider'],
    effect: 'Improve documentation before claim drops.',
    teaches: 'CDI is upstream of every medical-necessity denial.',
  },
  claim_scrubber: {
    id: 'claim_scrubber',
    name: 'Claim Scrubber',
    faction: 'vendor',
    damage: 18,
    accuracy: 92,
    turnCost: 1,
    effectiveFactions: ['vendor'],
    effect: 'Clean front-end edits. Strong vs vendor errors.',
    teaches: 'Front-end edits are 10x cheaper than back-end appeals.',
  },
  cob_check: {
    id: 'cob_check',
    name: 'COB Check',
    faction: 'employer',
    damage: 16,
    accuracy: 88,
    turnCost: 1,
    effectiveFactions: ['employer'],
    effect: 'Coordinate benefits. Blocks COB denials.',
    teaches: 'COB confusion is a Top-3 denial reason.',
  },
  medical_policy: {
    id: 'medical_policy',
    name: 'Policy Lookup',
    faction: 'payer',
    damage: 20,
    accuracy: 85,
    turnCost: 1,
    effectiveFactions: ['payer'],
    effect: 'Look up payer coverage rules before submitting.',
    teaches: 'Payer policies are public — most denials are predictable.',
  },
  cost_estimate: {
    id: 'cost_estimate',
    name: 'Cost Estimate',
    faction: 'patient',
    damage: 14,
    accuracy: 90,
    turnCost: 1,
    effectiveFactions: ['patient'],
    reputationDelta: 2,
    effect: 'Set patient expectations. Builds trust.',
    teaches: 'Same procedure, same plan, different deductible = different bill.',
  },
  aggressive_collections: {
    id: 'aggressive_collections',
    name: 'Collections',
    faction: 'provider',
    damage: 35,
    accuracy: 95,
    turnCost: 1,
    effectiveFactions: [],
    shadow: true,
    reputationDelta: -8,
    cashDelta: 10,
    effect: 'Heavy damage but costs reputation.',
    teaches: 'The provider was the bad guy this round.',
  },
  upcode: {
    id: 'upcode',
    name: 'Upcode',
    faction: 'provider',
    damage: 30,
    accuracy: 90,
    turnCost: 1,
    effectiveFactions: [],
    shadow: true,
    auditDelta: 8,
    cashDelta: 8,
    effect: 'Higher reimbursement. Increases audit risk.',
    teaches: 'This is fraud-adjacent. The auditor remembers.',
  },
}

export const TOOL_LIST = Object.values(TOOLS)
