import type { Encounter } from '../types'

export const ENCOUNTERS: Record<string, Encounter> = {
  intro_wrong_card: {
    id: 'intro_wrong_card',
    title: 'The Wrong Card',
    description:
      'Anjali handed her husband\'s card to the registrar. The claim went out under his subscriber id and bounced. One amend on Box 1a fixes it.',
    surfaceSymptom: 'Patient cannot be identified as our insured',
    rootCause: 'patient',
    carcCode: 'CO-31',
    carcName: 'Patient cannot be identified as our insured',
    watchpoint: 'The 271 eligibility response is the source of truth — not the card photocopy.',
    level: 1,
    archetype: 'Wrong Card',
    wing: 'eligibility',
    codexOnSight: 'obstacle_intro_wrong_card',
    puzzleSpecId: 'intro',
    cashRecovered: 387,
    caseId: 'case_intro_patel',
    highlightedBoxes: ['1a'],
    payerNote:
      'Subscriber AET447821903 (PATEL, RAVI) — dependent ANJALI PATEL listed under separate subscriber id AET447821491. Resubmit with Box 1a corrected.',
  },
  co_50: {
    id: 'co_50',
    title: 'Medical Necessity Wraith',
    description:
      'A semi-transparent figure of half-finished documentation. Won\'t resolve until you assemble enough supporting evidence — wrong moves only feed it.',
    surfaceSymptom: 'Payer denies medical necessity',
    rootCause: 'provider',
    carcCode: 'CO-50',
    carcName: 'Not medically necessary',
    watchpoint: 'CDI before coding prevents this; appeals after submission rarely fix it.',
    level: 4,
    archetype: 'Medical Necessity Wraith',
    wing: 'appeals',
    codexOnSight: 'obstacle_co_50',
    puzzleSpecId: 'wraith',
    unlocksOnDefeat: ['medical_policy'],
    caseId: 'case_wraith_walker',
    highlightedBoxes: ['21A', '24D-1'],
    payerNote:
      'TTE 93306 not medically necessary for I50.9 (heart failure, unspecified) without supporting evidence of LVEF<35% per LCD L33526.',
  },
  co_97: {
    id: 'co_97',
    title: 'Bundling Beast',
    description: 'Two services on the same day fused into one. The E&M was significant and separate, but the modifier is missing.',
    surfaceSymptom: 'Payer bundled the services together',
    rootCause: 'provider',
    carcCode: 'CO-97',
    carcName: 'Bundled / included',
    watchpoint: 'Modifier 25 / 59 logic is a coding-team responsibility.',
    level: 5,
    archetype: 'Bundling Beast',
    wing: 'coding',
    codexOnSight: 'obstacle_co_97',
    puzzleSpecId: 'bundle',
    caseId: 'case_bundle_kim',
    highlightedBoxes: ['24D-1'],
    payerNote:
      'CPT 99214 bundled into 11102 per NCCI edit. Append modifier -25 to the E&M to indicate a significant, separately identifiable service.',
  },
  co_197: {
    id: 'co_197',
    title: 'Prior Auth Gatekeeper',
    description:
      'A bureaucratic gate stands between the claim and adjudication. Every other move just bounces off the closed gate. File the 278 to bring it down.',
    surfaceSymptom: 'No prior auth on file',
    rootCause: 'payer',
    carcCode: 'CO-197',
    carcName: 'Precertification absent',
    watchpoint: 'Only fixable upstream — get the 278 before the visit.',
    level: 3,
    archetype: 'Prior Auth Gatekeeper',
    wing: 'appeals',
    codexOnSight: 'obstacle_co_197',
    puzzleSpecId: 'gatekeeper',
    unlocksOnDefeat: ['prior_auth_278'],
    caseId: 'case_gatekeeper_okafor',
    highlightedBoxes: ['24D-1'],
    payerNote:
      'CPT 72148 (MRI lumbar) requires prior authorization on file before adjudication. No 278 received — claim denied per UHC commercial policy CMP.PHARM.213.',
  },
  co_16_swarm: {
    id: 'co_16_swarm',
    title: 'Documentation Sprite Swarm',
    description:
      'Tiny gremlins keep peeling off a leaking chart. Each one is a missing-info reject. Killing them is endless until you patch the source upstream.',
    surfaceSymptom: '277CA front-end rejections piling up',
    rootCause: 'vendor',
    carcCode: 'CO-16',
    carcName: 'Missing/invalid information',
    watchpoint: 'CDI is upstream — patch the chart and the rejects stop. Scrubbing only sweeps what already came through.',
    level: 6,
    archetype: 'Documentation Sprite Swarm',
    wing: 'coding',
    codexOnSight: 'obstacle_co_16_swarm',
    puzzleSpecId: 'swarm',
    cashRecovered: 220,
    unlocksOnDefeat: ['claim_scrubber'],
    caseId: 'case_swarm_yamada',
    highlightedBoxes: ['21A', '24D-1'],
    payerNote:
      'Multiple 277CA rejects on file: missing rendering provider taxonomy and ambiguous diagnosis pointer. Resubmit with corrected loop 2310B PRV segment and specific dx.',
  },
  oa_23_hydra: {
    id: 'oa_23_hydra',
    title: 'COB Hydra',
    description:
      'Three heads. Three payers. Adjudicate them in order — Primary, then Secondary, then Tertiary — or you grow more heads.',
    surfaceSymptom: 'Multi-payer claim stuck in coordination',
    rootCause: 'payer', // first head is payer-rooted; others vary
    carcCode: 'OA-23',
    carcName: 'Adjustment / coordination by primary payer',
    watchpoint: 'COB sequence is contractual. The heads adjudicate in order — adjudicating out of order causes retractions.',
    level: 9,
    archetype: 'COB Hydra',
    wing: 'eligibility',
    codexOnSight: 'obstacle_oa_23_hydra',
    puzzleSpecId: 'hydra',
    cashRecovered: 1250,
    unlocksOnDefeat: ['cob_check'],
    caseId: 'case_hydra_okwu',
    highlightedBoxes: ['1', '4'],
    payerNote:
      'Secondary payer cannot adjudicate until primary remit is on file. Verify COB chain (BCBS / Medicare / Medicaid) and resequence per Medicare Secondary Payer rules.',
  },
  eligibility_fog: {
    id: 'eligibility_fog',
    title: 'Eligibility Fog',
    description:
      'A swirling gray cloud that hides everything: which payer, which plan, which benefits. Every swing is half-blind until the 270 inquiry burns it off.',
    surfaceSymptom: 'Coverage details unverifiable',
    rootCause: 'system',
    // No CARC — this is a process obstacle, not a denial code.
    watchpoint: '270/271 eligibility verification is cheap and prevents most "denials" from ever happening.',
    level: 2,
    archetype: 'Eligibility Fog',
    wing: 'eligibility',
    codexOnSight: 'obstacle_eligibility_fog',
    puzzleSpecId: 'fog',
    cashRecovered: 190,
    unlocksOnDefeat: ['cost_estimate'],
    caseId: 'case_fog_nguyen',
    highlightedBoxes: ['1a', '1'],
    payerNote:
      'Coverage cannot be confirmed for the subscriber on file. Run 270 inquiry to verify active member id and benefits before submission.',
  },
  co_18_doppelganger: {
    id: 'co_18_doppelganger',
    title: 'Duplicate Claim Doppelgänger',
    description:
      'A perfect copy of the claim already in the queue. Hit it with the same tool twice and the move bounces off you.',
    surfaceSymptom: 'Payer flagged the resubmission as a duplicate',
    rootCause: 'system',
    carcCode: 'CO-18',
    carcName: 'Duplicate claim',
    watchpoint: 'Same submission twice = the same denial twice. Vary the approach (837 frequency 7 instead of 1).',
    level: 9,
    archetype: 'Duplicate Claim Doppelgänger',
    wing: 'billing',
    codexOnSight: 'obstacle_co_18_doppelganger',
    puzzleSpecId: 'doppelganger',
    cashRecovered: 145,
    unlocksOnDefeat: ['submit_837i'],
    caseId: 'case_doppel_reyes',
    highlightedBoxes: ['1a', '24A-1'],
    payerNote:
      'Claim CLM-2026-03-08-19842 is a duplicate of one already on file. Submit as 837 frequency code 7 (replacement) to resolve.',
  },
  co_29_reaper: {
    id: 'co_29_reaper',
    title: 'Timely Filing Reaper',
    description:
      'A robed bureaucrat with an hourglass-blade. Each turn it sharpens. Time is the weapon, not the claim.',
    surfaceSymptom: 'Claim approaches the timely filing deadline.',
    rootCause: 'payer',
    carcCode: 'CO-29',
    carcName: 'Timely filing limit expired',
    watchpoint:
      'Timely filing is contractual. Once the deadline passes, no appeal will recover the claim.',
    level: 7,
    archetype: 'Timely Filing Reaper',
    wing: 'appeals',
    codexOnSight: 'obstacle_co_29_reaper',
    puzzleSpecId: 'reaper',
    cashRecovered: 1400,
    unlocksOnDefeat: ['submit_837i'],
    caseId: 'case_reaper_park',
    highlightedBoxes: ['24A-1'],
    payerNote:
      'Filing limit 180 days from DOS. Current claim filed 195 days post-service — denial per Aetna provider manual §6.4.',
  },
  boss_audit: {
    id: 'boss_audit',
    title: 'The Quarterly Audit',
    description: 'The payer is reviewing every recent claim. Every shortcut you took is about to surface.',
    surfaceSymptom: 'Payer demands documentation for all recent claims',
    rootCause: 'provider',
    carcCode: 'AUDIT',
    carcName: 'Quarterly Payer Audit',
    watchpoint: 'Audit risk is not abstract; it is a real expense. Every shortcut taken in earlier levels comes due here.',
    level: 10,
    archetype: 'The Quarterly Audit',
    wing: 'miracles',
    codexOnSight: 'obstacle_boss_audit',
    puzzleSpecId: 'audit-boss',
    cashRecovered: 8400,
    caseId: 'case_audit_finale',
    highlightedBoxes: ['67', '80'],
    payerNote:
      'Pre-payment audit per UHC commercial CMP.AUD.402. Documentation required for all inpatient stays > $5K within review window. Append rendering provider attestation, complete H&P, and discharge summary; verify principal dx supports DRG assignment.',
  },
  underpayment_specter: {
    id: 'underpayment_specter',
    title: 'Underpayment Specter',
    description: 'A claim that paid — but for less than the contract says. The shortfall hides inside a CO-45 adjustment.',
    surfaceSymptom: 'Contract-vs-paid variance flagged in monthly report',
    rootCause: 'payer',
    watchpoint: 'Underpayments are millions in aggregate. Read line-level numbers, not just batch totals.',
    level: 7,
    archetype: 'Underpayment Specter',
    wing: 'reconsideration',
    codexOnSight: 'obstacle_underpayment_specter',
    puzzleSpecId: 'specter',
    cashRecovered: 28,
  },
  lighthouse_charity: {
    id: 'lighthouse_charity',
    title: 'Lighthouse',
    description: 'A patient who needs the hospital\'s financial-assistance program applied correctly. The only encounter that\'s restorative, not adversarial.',
    surfaceSymptom: 'Patient cannot pay; uninsured at time of service',
    rootCause: 'patient',
    watchpoint: 'Charity care is the active path. Bad debt and payment-plan-only are passive failures dressed up as work.',
    level: 8,
    archetype: 'Lighthouse',
    wing: 'patient_services',
    codexOnSight: 'obstacle_lighthouse',
    puzzleSpecId: 'lighthouse',
    cashRecovered: 0,
  },
  surprise_bill_specter: {
    id: 'surprise_bill_specter',
    title: 'Surprise Bill Specter',
    description: 'An out-of-network ancillary bill in an in-network ER. NSA-protected; the patient owes in-network cost-share, not the OON balance.',
    surfaceSymptom: 'Patient received an OON balance bill from an ancillary provider',
    rootCause: 'vendor',
    watchpoint: 'NSA caps patient responsibility at in-network. Sending NSA-protected bills to collections is itself a regulatory violation.',
    level: 8,
    archetype: 'Surprise Bill Specter',
    wing: 'patient_services',
    codexOnSight: 'obstacle_surprise_bill',
    puzzleSpecId: 'surprise-bill',
    cashRecovered: 0,
  },
}

export const ENCOUNTER_LIST = Object.values(ENCOUNTERS)
