import type { EnemyDef } from '../types'

export const ENEMIES: Record<string, EnemyDef> = {
  co_11: {
    id: 'co_11',
    carcCode: 'CO-11',
    name: 'Diagnosis inconsistent w/ procedure',
    hp: 50,
    surfaceFaction: 'payer',
    rootFaction: 'provider',
    speed: 80,
    attackDamage: 12,
    attackCooldown: 2000,
    projectileSpeed: 200,
    counterFactions: ['provider'],
    description: 'The submitted diagnosis does not justify the procedure performed.',
    watchpoint: 'Documentation gaps drive medical-necessity denials, not the payer.',
  },
  co_16: {
    id: 'co_16',
    carcCode: 'CO-16',
    name: 'Missing/invalid information',
    hp: 40,
    surfaceFaction: 'payer',
    rootFaction: 'vendor',
    speed: 100,
    attackDamage: 8,
    attackCooldown: 1500,
    projectileSpeed: 250,
    counterFactions: ['vendor'],
    description: 'Required fields blank or malformed; rejected before adjudication.',
    watchpoint: 'Most "denials" engineers see are actually 277CA front-end rejects.',
  },
  co_22: {
    id: 'co_22',
    carcCode: 'CO-22',
    name: 'Care covered by another payer',
    hp: 45,
    surfaceFaction: 'payer',
    rootFaction: 'employer',
    speed: 70,
    attackDamage: 10,
    attackCooldown: 2200,
    projectileSpeed: 180,
    counterFactions: ['employer'],
    description: 'Another payer is primary; this one will not pay first.',
    watchpoint: 'COB chain is set at the employer / member-services layer.',
  },
  co_50: {
    id: 'co_50',
    carcCode: 'CO-50',
    name: 'Not medically necessary',
    hp: 65,
    surfaceFaction: 'payer',
    rootFaction: 'provider',
    speed: 60,
    attackDamage: 16,
    attackCooldown: 2500,
    projectileSpeed: 220,
    counterFactions: ['provider', 'payer'],
    description: 'Payer rules deem the service unnecessary for the documented condition.',
    watchpoint: 'CDI before coding prevents this; appeals after submission rarely fix it.',
  },
  co_97: {
    id: 'co_97',
    carcCode: 'CO-97',
    name: 'Bundled / included',
    hp: 55,
    surfaceFaction: 'payer',
    rootFaction: 'provider',
    speed: 75,
    attackDamage: 14,
    attackCooldown: 1800,
    projectileSpeed: 200,
    counterFactions: ['provider'],
    description: 'Service is part of another billed procedure; modifier missing or wrong.',
    watchpoint: 'Modifier 25 / 59 logic is a coding-team responsibility.',
  },
  co_109: {
    id: 'co_109',
    carcCode: 'CO-109',
    name: 'Not covered by this payer',
    hp: 40,
    surfaceFaction: 'payer',
    rootFaction: 'patient',
    speed: 90,
    attackDamage: 10,
    attackCooldown: 1600,
    projectileSpeed: 240,
    counterFactions: ['patient', 'provider'],
    description: 'Patient gave wrong plan info at registration.',
    watchpoint: 'Patient-portal eligibility beats re-keyed registration data.',
  },
  co_197: {
    id: 'co_197',
    carcCode: 'CO-197',
    name: 'Precertification absent',
    hp: 60,
    surfaceFaction: 'payer',
    rootFaction: 'provider',
    speed: 65,
    attackDamage: 18,
    attackCooldown: 2800,
    projectileSpeed: 250,
    counterFactions: ['payer'],
    description: 'No prior authorization on file for this service.',
    watchpoint: 'Only fixable upstream — get the 278 before the visit.',
  },
  oa_23: {
    id: 'oa_23',
    carcCode: 'OA-23',
    name: 'Adjustment by primary payer',
    hp: 35,
    surfaceFaction: 'payer',
    rootFaction: 'employer',
    speed: 85,
    attackDamage: 8,
    attackCooldown: 1400,
    projectileSpeed: 200,
    counterFactions: ['employer'],
    description: 'Primary payer adjusted; you must coordinate or rebill secondary.',
    watchpoint: 'Treat OA-23 as workflow, not denial.',
  },
  pr_204: {
    id: 'pr_204',
    carcCode: 'PR-204',
    name: 'Not covered under patient plan',
    hp: 45,
    surfaceFaction: 'payer',
    rootFaction: 'employer',
    speed: 70,
    attackDamage: 12,
    attackCooldown: 2000,
    projectileSpeed: 200,
    counterFactions: ['employer', 'patient'],
    description: "Benefit exclusion in the patient's specific plan design.",
    watchpoint: 'Bill the patient correctly — appeals will not change a benefit exclusion.',
  },
  reject_277ca: {
    id: 'reject_277ca',
    carcCode: '277CA',
    name: 'Front-end rejection',
    hp: 30,
    surfaceFaction: 'vendor',
    rootFaction: 'vendor',
    speed: 120,
    attackDamage: 6,
    attackCooldown: 1200,
    projectileSpeed: 280,
    counterFactions: ['vendor'],
    description: 'Clearinghouse rejected the claim before payer ever saw it.',
    watchpoint: 'Not a denial — fix and resubmit fast.',
  },
  boss_payer_audit: {
    id: 'boss_payer_audit',
    carcCode: 'AUDIT',
    name: 'Quarterly Payer Audit',
    hp: 180,
    surfaceFaction: 'payer',
    rootFaction: 'provider',
    speed: 45,
    attackDamage: 20,
    attackCooldown: 3000,
    projectileSpeed: 300,
    counterFactions: ['provider'],
    description: 'Payer demands documentation for every recent claim.',
    watchpoint: 'Audit risk is not abstract; it is a real expense.',
  },
}

export const ENEMY_LIST = Object.values(ENEMIES)
