import type { Encounter } from '../types'

export const ENCOUNTERS: Record<string, Encounter> = {
  co_11: {
    id: 'co_11',
    title: 'The Inconsistent Diagnosis',
    description: 'A surgeon performed a procedure, but the documented diagnosis doesn\'t match. The payer flagged it.',
    surfaceSymptom: 'Payer says diagnosis doesn\'t justify the procedure',
    rootCause: 'provider',
    hp: 50,
    attackDamage: 12,
    carcCode: 'CO-11',
    carcName: 'Diagnosis inconsistent with procedure',
    watchpoint: 'Documentation gaps drive medical-necessity denials, not the payer.',
    correctTools: ['cdi_query', 'appeal_letter'],
    level: 4,
  },
  co_16: {
    id: 'co_16',
    title: 'The Missing Field',
    description: 'A claim was rejected before the payer ever saw it. Required fields were blank or malformed.',
    surfaceSymptom: 'Clearinghouse rejected — missing information',
    rootCause: 'vendor',
    hp: 40,
    attackDamage: 8,
    carcCode: 'CO-16',
    carcName: 'Missing/invalid information',
    watchpoint: 'Most "denials" engineers see are actually 277CA front-end rejects.',
    correctTools: ['claim_scrubber'],
    level: 6,
  },
  co_22: {
    id: 'co_22',
    title: 'The Other Payer',
    description: 'The claim was sent to the wrong insurance. Another payer is primary.',
    surfaceSymptom: 'Payer says another plan should pay first',
    rootCause: 'employer',
    hp: 45,
    attackDamage: 10,
    carcCode: 'CO-22',
    carcName: 'Care covered by another payer',
    watchpoint: 'COB chain is set at the employer / member-services layer.',
    correctTools: ['cob_check', 'eligibility_270'],
    level: 2,
    unlocksOnDefeat: ['cob_check'],
  },
  co_50: {
    id: 'co_50',
    title: 'Medical Necessity Wraith',
    description:
      'A semi-transparent figure of half-finished documentation. Won\'t resolve until you assemble enough supporting evidence — wrong moves only feed it.',
    surfaceSymptom: 'Payer denies medical necessity',
    rootCause: 'provider',
    hp: 1, // unused by Investigation; kept for backward compat / display
    attackDamage: 0,
    carcCode: 'CO-50',
    carcName: 'Not medically necessary',
    watchpoint: 'CDI before coding prevents this; appeals after submission rarely fix it.',
    correctTools: ['cdi_query', 'medical_policy'],
    level: 4,
    archetype: 'Medical Necessity Wraith',
    wing: 'appeals',
    mechanic: 'investigation',
    codexOnSight: 'obstacle_co_50',
    puzzleSpecId: 'wraith',
    unlocksOnDefeat: ['medical_policy'],
    caseId: 'case_wraith_walker',
    highlightedBoxes: ['21A', '24D-1'],
    payerNote:
      'TTE 93306 not medically necessary for I50.9 (heart failure, unspecified) without supporting evidence of LVEF<35% per LCD L33526.',
    toolEffects: {
      // Investigation actions visibly annotate the form as the player
      // assembles evidence. Mirrors the case-file fact-finding loop.
      lookup:   [{ box: '24D-1', kind: 'note', value: 'LCD L33526 reviewed' }],
      document: [{ box: '21A',   kind: 'check' }],
      decide:   [{ box: '24D-1', kind: 'stamp', value: 'APPEAL' }],
    },
    caseFile: {
      threshold: 3,
      intro: 'From the chart and the LCD:',
      facts: [
        {
          id: 'ckd_history',
          label: 'Patient has chronic kidney disease, stage 3',
          relevance: 'relevant',
          onReveal: { box: '21A', kind: 'note', value: 'CKD III' },
        },
        {
          id: 'lcd_creatinine',
          label: 'LCD requires creatinine > 2.5 mg/dL for coverage',
          relevance: 'relevant',
          onReveal: { box: '24D-1', kind: 'note', value: 'LCD: creat > 2.5' },
        },
        {
          id: 'labs_recent',
          label: 'Labs from 3 months ago show creatinine 2.8',
          relevance: 'relevant',
          weakOnReveal: true,
          onReveal: { box: '21A', kind: 'note', value: 'creat 2.8 (3mo old)' },
        },
        {
          id: 'symptoms_doc',
          label: 'Documented fatigue, edema, declining GFR',
          relevance: 'relevant',
          weakOnReveal: true,
          onReveal: { box: '21A', kind: 'note', value: 'sx: fatigue, edema' },
        },
        {
          id: 'wrong_tuesday',
          label: 'Procedure was performed at 9:00 AM Tuesday',
          relevance: 'distractor',
        },
        {
          id: 'wrong_zone',
          label: 'Patient lives in service-area Zone 2',
          relevance: 'distractor',
        },
        {
          id: 'wrong_referrer',
          label: 'Referring provider is in-network',
          relevance: 'distractor',
        },
      ],
    },
    puzzleDraft: {
      premise:
        'CO-50 medical necessity: payer denies a TTE (93306) for unspecified heart failure (I50.9), citing LCD L33526 which requires evidence of LVEF<35% or specific symptomatology. Investigate the chart and the LCD; build a defensible case before pressing DECIDE.',
      issues: [
        {
          label: 'Read the LCD — what does the payer actually require?',
          resolvedBy: 'lookup',
          teaching: 'Most medical-necessity denials are predictable. The policy is public; read it before you appeal.',
        },
        {
          label: 'Find supporting clinical evidence in the chart',
          hidden: true,
          resolvedBy: 'investigate',
          teaching: 'Chart often has the evidence but it\'s scattered (CKD III, recent labs, sx documentation).',
        },
        {
          label: 'Document the connection (weak facts → strong)',
          hidden: true,
          resolvedBy: 'document',
          teaching: 'Weak evidence flags need explicit linkage to the LCD criteria — that\'s the CDI loop.',
        },
        {
          label: 'Decide: submit appeal with documented packet',
          hidden: true,
          resolvedBy: 'decide',
          teaching: 'Decide is irreversible. If the evidence isn\'t there yet, you lose the appeal — and the claim.',
        },
      ],
      winCondition: 'Threshold of strong-supporting facts met → Decide → appeal accepted.',
      costs: [
        'Decide too early (below threshold): appeal denied, claim closes, +10 stress, +1 audit risk.',
        'Documenting a distractor fact (e.g. service-area Zone 2): wastes a turn off the filing window with no progress.',
        'Skipping Lookup: you\'ll be guessing what evidence the LCD demands.',
      ],
      payerReplies: {
        lookup: 'LCD L33526 requires LVEF<35% OR creatinine > 2.5 with documented symptomatology to support medical necessity.',
        investigate: '(reveals one fact from the chart — relevant or distractor)',
        document: 'Fact upgraded — explicitly linked to LCD criteria. (or: distractor noted, no progress)',
        decide_pass: 'Appeal accepted. CDI packet supports medical necessity per LCD. Claim adjudicates.',
        decide_fail: 'Appeal denied. Insufficient documentation linking clinical evidence to LCD requirements. Claim closes.',
      },
      notes:
        'The Wraith already runs as Investigation — this draft just makes the issue checklist + payer-reply structure explicit so the player sees the puzzle shape, not just a turn budget. Most of the work is already done in InvestigationController; the reframe is mostly UI / messaging.',
    },
  },
  co_97: {
    id: 'co_97',
    title: 'Bundling Beast',
    description: 'Two services on the same day fused into one. The E&M was significant and separate, but the modifier is missing.',
    surfaceSymptom: 'Payer bundled the services together',
    rootCause: 'provider',
    hp: 55,
    attackDamage: 14,
    carcCode: 'CO-97',
    carcName: 'Bundled / included',
    watchpoint: 'Modifier 25 / 59 logic is a coding-team responsibility.',
    correctTools: ['claim_scrubber', 'cdi_query'],
    level: 5,
    archetype: 'Bundling Beast',
    wing: 'coding',
    codexOnSight: 'obstacle_co_97',
    puzzleSpecId: 'bundle',
    caseId: 'case_bundle_kim',
    highlightedBoxes: ['24D-1'],
    payerNote:
      'CPT 99214 bundled into 11102 per NCCI edit. Append modifier -25 to the E&M to indicate a significant, separately identifiable service.',
    toolEffects: {
      // CDI Query is the canonical fix here — mod-25 stamped onto the
      // E&M line. Claim Scrubber catches the missing modifier; Resubmit
      // takes the fixed claim out the door. Appeal escalates if the
      // first pass didn't go.
      cdi_query:     [{ box: '24D-1', kind: 'stamp', value: '+25 mod' }],
      claim_scrubber:[{ box: '24D-1', kind: 'note',  value: 'NCCI checked' }],
      submit_837p:   [{ box: '24D-1', kind: 'check' }],
      appeal_letter: [{ box: '24D-1', kind: 'stamp', value: 'APPEAL' }],
      medical_policy:[{ box: '24D-1', kind: 'note',  value: 'NCCI policy ref' }],
    },
    puzzleDraft: {
      premise:
        'A claim came back CO-97. The payer says 99214 was bundled into 11102 per NCCI. Reading the chart, the E&M was significant and separately identifiable from the lesion removal — but the claim went out without modifier 25.',
      issues: [
        {
          label: 'Why was this bundled? (NCCI edit pair, not a bundling error)',
          resolvedBy: 'medical_policy',
          teaching: 'Reading the actual NCCI rationale before reaching for tools — most bundles are unbundlable with the right modifier.',
        },
        {
          label: 'Modifier 25 missing on E&M (24D line 1)',
          hidden: true,
          resolvedBy: 'cdi_query',
          teaching: 'CDI clarifies that the E&M was significant and separately identifiable, justifying mod-25.',
        },
        {
          label: 'Resubmit cleanly (no NCCI edit triggers on rescrub)',
          hidden: true,
          resolvedBy: 'claim_scrubber',
          teaching: 'Rescrub before resubmit — confirms the modifier addition cleared the front-end edit.',
        },
      ],
      winCondition: 'All three issues resolved → Submit Replacement → claim adjudicates clean.',
      costs: [
        'Premature Appeal Letter: −2 days off filing window, +5 stress; payer responds "claim correction required first".',
        'Submitting before mod-25 added: re-denied with same CO-97 + new RARC, +1 attempt counter (3 max).',
        'Wrong modifier (e.g. 59 instead of 25): payer responds "modifier 59 inappropriate; documentation supports 25".',
      ],
      payerReplies: {
        medical_policy: 'NCCI edit pair 11102/99214 reviewed. E&M may be unbundled with modifier 25 if significant and separately identifiable.',
        cdi_query: 'Rendering provider attests E&M was significant and separately identifiable. Modifier 25 added to line 1.',
        appeal_letter: 'Appeal premature. Resubmit corrected claim with appropriate modifier first; appeal only after second denial.',
        submit_837p: '✓ Claim accepted. CCI edits cleared. Adjudication pending.',
      },
      notes:
        'This is the lightest possible reframe — the existing toolEffects already do the right things visually. The reframe just adds (1) a visible issue checklist instead of an HP bar, (2) explicit payer reply text after each move, and (3) wrong-move costs that aren\'t damage rolls.',
    },
  },
  co_109: {
    id: 'co_109',
    title: 'Wrong Insurance Card',
    description: 'The patient gave old insurance info at check-in. The claim went to a plan that no longer covers them.',
    surfaceSymptom: 'Payer says patient isn\'t covered',
    rootCause: 'patient',
    hp: 40,
    attackDamage: 10,
    carcCode: 'CO-109',
    carcName: 'Not covered by this payer',
    watchpoint: 'Patient-portal eligibility beats re-keyed registration data.',
    correctTools: ['eligibility_270'],
    level: 2,
    unlocksOnDefeat: ['cost_estimate'],
  },
  co_197: {
    id: 'co_197',
    title: 'Prior Auth Gatekeeper',
    description:
      'A bureaucratic gate stands between the claim and adjudication. Every other move just bounces off the closed gate. File the 278 to bring it down.',
    surfaceSymptom: 'No prior auth on file',
    rootCause: 'payer',
    hp: 60,
    attackDamage: 14,
    carcCode: 'CO-197',
    carcName: 'Precertification absent',
    watchpoint: 'Only fixable upstream — get the 278 before the visit.',
    correctTools: ['prior_auth_278'],
    level: 3,
    archetype: 'Prior Auth Gatekeeper',
    wing: 'appeals',
    mechanic: 'block',
    codexOnSight: 'obstacle_co_197',
    unlocksOnDefeat: ['prior_auth_278'],
    caseId: 'case_gatekeeper_okafor',
    highlightedBoxes: ['24D-1'],
    payerNote:
      'CPT 72148 (MRI lumbar) requires prior authorization on file before adjudication. No 278 received — claim denied per UHC commercial policy CMP.PHARM.213.',
    toolEffects: {
      prior_auth_278: [
        { box: '24D-1', kind: 'check' },
        { box: '24D-1', kind: 'note', value: '278 on file — gate down' },
      ],
      // Other tools land checks if used after the gate falls.
      submit_837p:    [{ box: '24D-1', kind: 'check' }],
      claim_scrubber: [{ box: '24D-1', kind: 'note', value: 'rescrubbed' }],
      cdi_query:      [{ box: '21A',   kind: 'note', value: 'supporting docs' }],
      appeal_letter:  [{ box: '24D-1', kind: 'stamp', value: 'APPEAL' }],
    },
    puzzleDraft: {
      premise:
        'CPT 72148 (MRI lumbar) was denied — no prior auth on file. The patient already had the scan; you have a denied claim and a closed gate. The 278 is the only key.',
      issues: [
        {
          label: 'Read the policy — what auth is required and how?',
          resolvedBy: 'medical_policy',
          teaching: 'Auth requirements live in payer policy. UHC CMP.PHARM.213 specifies the 278 channel and turnaround.',
        },
        {
          label: 'File the 278 retroactively',
          resolvedBy: 'prior_auth_278',
          teaching: 'Most payers allow retroactive 278 within X days post-service for emergent / unplanned imaging. The 278 is the actual transaction.',
        },
        {
          label: 'Document medical necessity for the retro auth',
          hidden: true,
          resolvedBy: 'cdi_query',
          teaching: 'Retro 278s require justification — the chart needs to show why pre-auth wasn\'t feasible.',
        },
        {
          label: 'Resubmit with auth number on Box 23',
          hidden: true,
          resolvedBy: 'submit_837p',
          teaching: 'Box 23 (prior auth number) connects the 278 to the claim. Without it, the gate stays closed.',
        },
      ],
      winCondition: 'Auth approved + auth number populated + claim resubmitted → adjudication.',
      costs: [
        'Submit before 278: claim re-denies CO-197, no progress, −1 day off filing window.',
        'Appeal Letter without 278: payer responds "appeal premature; obtain authorization first".',
        'Wrong tool against the gate: explicit "GATE CLOSED — 278 required" reply, no damage abstraction.',
      ],
      payerReplies: {
        prior_auth_278: 'Retro 278 received. Pending medical-necessity review. Auth number AUTH-9981420 issued; populate Box 23 on resubmission.',
        medical_policy: 'CMP.PHARM.213: MRI lumbar requires prior auth via 278. Retroactive submissions accepted within 14 days of service for emergent presentations.',
        appeal_letter: 'Appeal premature — no authorization on file. Submit 278 first.',
        submit_837p: '✓ Claim accepted with auth on file. Adjudication pending.',
      },
      notes:
        'Block becomes "the gate is the puzzle." Today the gate just makes alternating turns useless; the reframe makes it a discrete obstacle that the 278 specifically unlocks. Other tools have explicit replies instead of "did 0 damage."',
    },
  },
  co_16_swarm: {
    id: 'co_16_swarm',
    title: 'Documentation Sprite Swarm',
    description:
      'Tiny gremlins keep peeling off a leaking chart. Each one is a missing-info reject. Killing them is endless until you patch the source upstream.',
    surfaceSymptom: '277CA front-end rejections piling up',
    rootCause: 'vendor',
    hp: 75,
    attackDamage: 6,
    carcCode: 'CO-16',
    carcName: 'Missing/invalid information',
    watchpoint: 'CDI is upstream — patch the chart and the rejects stop. Scrubbing only sweeps what already came through.',
    correctTools: ['cdi_query', 'claim_scrubber'],
    level: 6,
    archetype: 'Documentation Sprite Swarm',
    wing: 'coding',
    mechanic: 'spawn',
    codexOnSight: 'obstacle_co_16_swarm',
    cashRecovered: 220,
    unlocksOnDefeat: ['claim_scrubber'],
    caseId: 'case_swarm_yamada',
    highlightedBoxes: ['21A', '24D-1'],
    payerNote:
      'Multiple 277CA rejects on file: missing rendering provider taxonomy and ambiguous diagnosis pointer. Resubmit with corrected loop 2310B PRV segment and specific dx.',
    toolEffects: {
      cdi_query:      [{ box: '21A',   kind: 'note',  value: 'chart patched' }],
      claim_scrubber: [{ box: '24D-1', kind: 'note',  value: 'edits cleaned' }],
      submit_837p:    [{ box: '24D-1', kind: 'check' }],
      appeal_letter:  [{ box: '24D-1', kind: 'stamp', value: 'APPEAL' }],
    },
  },
  oa_23: {
    id: 'oa_23',
    title: 'The Coordination Gap',
    description: 'The primary payer adjusted payment, but nobody coordinated with the secondary.',
    surfaceSymptom: 'Primary payer adjusted; secondary confused',
    rootCause: 'employer',
    hp: 35,
    attackDamage: 8,
    carcCode: 'OA-23',
    carcName: 'Adjustment by primary payer',
    watchpoint: 'Treat OA-23 as workflow, not denial.',
    correctTools: ['cob_check'],
    level: 7,
  },
  oa_23_hydra: {
    id: 'oa_23_hydra',
    title: 'COB Hydra',
    description:
      'Three heads. Three payers. Adjudicate them in order — Primary, then Secondary, then Tertiary — or you grow more heads.',
    surfaceSymptom: 'Multi-payer claim stuck in coordination',
    rootCause: 'payer', // first head is payer-rooted; others vary
    hp: 90,
    attackDamage: 12,
    carcCode: 'OA-23',
    carcName: 'Adjustment / coordination by primary payer',
    watchpoint: 'COB sequence is contractual. The heads adjudicate in order — adjudicating out of order causes retractions.',
    correctTools: ['cob_check', 'medical_policy', 'submit_837p'],
    level: 9,
    archetype: 'COB Hydra',
    wing: 'eligibility',
    mechanic: 'multiHead',
    codexOnSight: 'obstacle_oa_23_hydra',
    cashRecovered: 1250,
    unlocksOnDefeat: ['cob_check'],
    caseId: 'case_hydra_okwu',
    highlightedBoxes: ['1', '4'],
    payerNote:
      'Secondary payer cannot adjudicate until primary remit is on file. Verify COB chain (BCBS / Medicare / Medicaid) and resequence per Medicare Secondary Payer rules.',
    toolEffects: {
      cob_check:      [{ box: '1', kind: 'note',  value: 'COB resequenced' }],
      medical_policy: [{ box: '1', kind: 'note',  value: 'MSP rule applied' }],
      submit_837p:    [{ box: '4', kind: 'check' }],
      eligibility_270:[{ box: '1', kind: 'check' }],
    },
  },
  pr_204: {
    id: 'pr_204',
    title: 'The Benefit Exclusion',
    description: 'The service isn\'t covered under the patient\'s specific plan design. No appeal will change it.',
    surfaceSymptom: 'Service excluded from patient\'s benefits',
    rootCause: 'employer',
    hp: 45,
    attackDamage: 12,
    carcCode: 'PR-204',
    carcName: 'Not covered under patient plan',
    watchpoint: 'Bill the patient correctly — appeals will not change a benefit exclusion.',
    correctTools: ['eligibility_270', 'cost_estimate'],
    level: 9,
    unlocksOnDefeat: ['cost_estimate'],
  },
  reject_277ca: {
    id: 'reject_277ca',
    title: 'The Front-End Reject',
    description: 'The clearinghouse kicked the claim back before the payer saw it. Something in the EDI format was wrong.',
    surfaceSymptom: 'Clearinghouse returned a 277CA rejection',
    rootCause: 'vendor',
    hp: 30,
    attackDamage: 6,
    carcCode: '277CA',
    carcName: 'Front-end rejection',
    watchpoint: 'Not a denial — fix and resubmit fast.',
    correctTools: ['claim_scrubber'],
    level: 6,
  },
  eligibility_fog: {
    id: 'eligibility_fog',
    title: 'Eligibility Fog',
    description:
      'A swirling gray cloud that hides everything: which payer, which plan, which benefits. Every swing is half-blind until the 270 inquiry burns it off.',
    surfaceSymptom: 'Coverage details unverifiable',
    rootCause: 'system',
    hp: 50,
    attackDamage: 9,
    // No CARC — this is a process obstacle, not a denial code.
    watchpoint: '270/271 eligibility verification is cheap and prevents most "denials" from ever happening.',
    correctTools: ['eligibility_270'],
    level: 2,
    archetype: 'Eligibility Fog',
    wing: 'eligibility',
    mechanic: 'blind',
    codexOnSight: 'obstacle_eligibility_fog',
    cashRecovered: 190,
    unlocksOnDefeat: ['cost_estimate'],
    caseId: 'case_fog_nguyen',
    highlightedBoxes: ['1a', '1'],
    payerNote:
      'Coverage cannot be confirmed for the subscriber on file. Run 270 inquiry to verify active member id and benefits before submission.',
    toolEffects: {
      eligibility_270: [
        { box: '1a', kind: 'check' },
        { box: '1a', kind: 'note', value: '270/271 verified' },
      ],
      cost_estimate:  [{ box: '1',  kind: 'note',  value: 'good-faith estimate' }],
      submit_837p:    [{ box: '1a', kind: 'check' }],
      claim_scrubber: [{ box: '1a', kind: 'note',  value: 'eligibility revalidated' }],
    },
  },
  co_18_doppelganger: {
    id: 'co_18_doppelganger',
    title: 'Duplicate Claim Doppelgänger',
    description:
      'A perfect copy of the claim already in the queue. Hit it with the same tool twice and the move bounces off you.',
    surfaceSymptom: 'Payer flagged the resubmission as a duplicate',
    rootCause: 'system',
    hp: 60,
    attackDamage: 10,
    carcCode: 'CO-18',
    carcName: 'Duplicate claim',
    watchpoint: 'Same submission twice = the same denial twice. Vary the approach (837 frequency 7 instead of 1).',
    correctTools: ['claim_scrubber', 'submit_837p'],
    level: 6,
    archetype: 'Duplicate Claim Doppelgänger',
    wing: 'billing',
    mechanic: 'mirror',
    codexOnSight: 'obstacle_co_18_doppelganger',
    cashRecovered: 145,
    unlocksOnDefeat: ['submit_837i'],
    caseId: 'case_doppel_reyes',
    highlightedBoxes: ['1a', '24A-1'],
    payerNote:
      'Claim CLM-2026-03-08-19842 is a duplicate of one already on file. Submit as 837 frequency code 7 (replacement) to resolve.',
    toolEffects: {
      // submit_837p resolves the duplicate when used (not repeated) by
      // adding the frequency-7 stamp — the canonical replacement code.
      submit_837p:    [{ box: '24A-1', kind: 'stamp', value: '+fcy 7' }],
      claim_scrubber: [{ box: '1a',    kind: 'note',  value: 'dup check' }],
      cdi_query:      [{ box: '21A',   kind: 'note',  value: 'note clarified' }],
      eligibility_270:[{ box: '1a',    kind: 'check' }],
    },
  },
  co_29_reaper: {
    id: 'co_29_reaper',
    title: 'Timely Filing Reaper',
    description:
      'A robed bureaucrat with an hourglass-blade. Each turn it sharpens. Time is the weapon, not the claim.',
    surfaceSymptom: 'Claim approaches the timely filing deadline.',
    rootCause: 'payer',
    hp: 70,
    attackDamage: 8, // base; escalates by +4 per day lost
    carcCode: 'CO-29',
    carcName: 'Timely filing limit expired',
    watchpoint:
      'Timely filing is contractual. Once the deadline passes, no appeal will recover the claim.',
    correctTools: ['claim_scrubber', 'submit_837p'],
    level: 7,
    archetype: 'Timely Filing Reaper',
    wing: 'appeals',
    mechanic: 'timed',
    codexOnSight: 'obstacle_co_29_reaper',
    puzzleSpecId: 'reaper',
    cashRecovered: 1400,
    unlocksOnDefeat: ['submit_837i'],
    caseId: 'case_reaper_park',
    highlightedBoxes: ['24A-1'],
    payerNote:
      'Filing limit 180 days from DOS. Current claim filed 195 days post-service — denial per Aetna provider manual §6.4.',
    toolEffects: {
      submit_837p:    [{ box: '24A-1', kind: 'check' }],
      appeal_letter:  [{ box: '24A-1', kind: 'stamp', value: '+30d ext' }],
      claim_scrubber: [{ box: '24A-1', kind: 'note',  value: 'expedited' }],
      cdi_query:      [{ box: '21A',   kind: 'note',  value: 'amended note' }],
    },
  },
  boss_audit: {
    id: 'boss_audit',
    title: 'The Quarterly Audit',
    description: 'The payer is reviewing every recent claim. Every shortcut you took is about to surface.',
    surfaceSymptom: 'Payer demands documentation for all recent claims',
    rootCause: 'provider',
    hp: 120,
    attackDamage: 20,
    carcCode: 'AUDIT',
    carcName: 'Quarterly Payer Audit',
    watchpoint: 'Audit risk is not abstract; it is a real expense. Every shortcut taken in earlier levels comes due here.',
    correctTools: ['cdi_query', 'claim_scrubber', 'medical_policy'],
    level: 10,
    archetype: 'The Quarterly Audit',
    wing: 'miracles',
    mechanic: 'audit',
    codexOnSight: 'obstacle_boss_audit',
    cashRecovered: 8400,
    caseId: 'case_audit_finale',
    highlightedBoxes: ['67', '80'],
    payerNote:
      'Pre-payment audit per UHC commercial CMP.AUD.402. Documentation required for all inpatient stays > $5K within review window. Append rendering provider attestation, complete H&P, and discharge summary; verify principal dx supports DRG assignment.',
    toolEffects: {
      cdi_query:      [{ box: '67', kind: 'note',  value: 'attestation on file' }],
      medical_policy: [{ box: '80', kind: 'note',  value: 'CMP.AUD.402 reviewed' }],
      claim_scrubber: [{ box: '80', kind: 'check' }],
      submit_837i:    [{ box: '80', kind: 'check' }],
      appeal_letter:  [{ box: '80', kind: 'stamp', value: 'APPEAL' }],
      // Shadow tools land a "RECEIPT" stamp — visual reminder of the heal.
      upcode:                 [{ box: '67', kind: 'stamp', value: 'RECEIPT' }],
      aggressive_collections: [{ box: '67', kind: 'stamp', value: 'RECEIPT' }],
    },
  },
}

export const ENCOUNTER_LIST = Object.values(ENCOUNTERS)
