import type { LevelDef } from '../types'

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    title: 'Orientation',
    subtitle: 'Your first day. A claim goes missing.',
    hospitalDescription: 'The revenue cycle office. Desks, monitors, and the hum of fluorescent lights.',
    waitingRoomDescription: 'An endless waiting room. Rows of chairs. A ticket counter that never moves.',
    concepts: ['denial_rate', 'co_109', 'x12_270_271', 'eligibility'],
    encounters: ['intro_wrong_card'],
    cases: ['case_intro_patel'],
    npcsActive: ['anjali', 'dana', 'kim', 'jordan'],
    bossEncounter: undefined,
  },
  {
    id: 2,
    title: 'The Front Door',
    subtitle: 'Registration is where claims are born — and where they first break.',
    hospitalDescription: 'The registration desk. Stacks of insurance cards and a line out the door.',
    waitingRoomDescription: 'The chairs have started to face different directions. The clock ticks backwards.',
    concepts: ['cms1500', 'x12_837', 'icd10_cm', 'cpt'],
    encounters: ['eligibility_fog'],
    cases: ['case_level1_cms', 'case_fog_nguyen'],
    npcsActive: ['dana', 'kim', 'alex'],
  },
  {
    id: 3,
    title: 'The Gate',
    subtitle: 'Prior authorization. The payer says: prove it first.',
    hospitalDescription: 'The pre-certification office. Phone on hold. Fax machine grinding.',
    waitingRoomDescription: 'A gate with no gatekeeper. Forms flutter through the bars.',
    concepts: ['prior_auth', 'x12_278', 'medical_necessity'],
    encounters: ['co_197', 'co_50'],
    cases: ['case_gatekeeper_okafor', 'case_wraith_walker'],
    npcsActive: ['dana', 'martinez', 'sam'],
  },
  {
    id: 4,
    title: 'The Copy',
    subtitle: 'Clinical documentation meets billing codes.',
    hospitalDescription: 'The HIM department. Charts, codes, and the CDI team.',
    waitingRoomDescription: 'Carbon copies of documents, each slightly different from the last.',
    concepts: ['cdi', 'icd10_cm', 'icd10_pcs', 'modifiers'],
    encounters: ['co_97'],
    cases: ['case_level1_ub', 'case_bundle_kim'],
    npcsActive: ['martinez', 'pat'],
  },
  {
    id: 5,
    title: 'The Library',
    subtitle: 'Payer policies are public. Most denials are predictable.',
    hospitalDescription: 'The contract management office. Binders of payer agreements.',
    waitingRoomDescription: 'Infinite shelves of policy manuals. The pages rearrange when you look away.',
    concepts: ['medical_policy', 'fee_schedule', 'contract_terms'],
    encounters: ['co_50'],
    cases: ['case_wraith_walker'],
    npcsActive: ['dana', 'sam'],
  },
  {
    id: 6,
    title: 'The Conveyor',
    subtitle: 'The claim drops. Clearinghouse, payer, adjudication.',
    hospitalDescription: 'The billing office. Claims queued and dropping.',
    waitingRoomDescription: 'A conveyor belt carrying forms into darkness. Some fall off.',
    concepts: ['x12_837', 'x12_277ca', 'clearinghouse', 'adjudication'],
    encounters: ['co_16_swarm', 'co_18_doppelganger'],
    cases: ['case_swarm_yamada', 'case_doppel_reyes'],
    npcsActive: ['alex', 'pat'],
  },
  {
    id: 7,
    title: 'The Courtroom',
    subtitle: 'The remittance arrives. Time to read the verdict.',
    hospitalDescription: 'The payment posting area. ERAs streaming in.',
    waitingRoomDescription: 'A courtroom where the judge is a rubber stamp.',
    concepts: ['x12_835', 'carc_rarc', 'remittance', 'adjustment'],
    encounters: ['co_50', 'co_97', 'co_29_reaper'],
    cases: ['case_reaper_park'],
    npcsActive: ['sam', 'jordan'],
  },
  {
    id: 8,
    title: 'The River',
    subtitle: 'Patient responsibility. The bill flows downstream.',
    hospitalDescription: 'Patient financial services. The phone rings constantly.',
    waitingRoomDescription: 'A river of paper bills, flowing toward patients who cannot see them coming.',
    concepts: ['cost_share', 'deductible', 'coinsurance', 'copay', 'oop_max'],
    encounters: ['surprise_bill_specter', 'lighthouse_charity'],
    cases: [],
    npcsActive: ['jordan', 'dana'],
  },
  {
    id: 9,
    title: 'The Maze',
    subtitle: 'Coordination of benefits. Multiple payers, one claim.',
    hospitalDescription: 'The COB desk. Spreadsheets tracking primary, secondary, tertiary.',
    waitingRoomDescription: 'Hallways that split and merge. Every turn leads to another payer.',
    concepts: ['cob', 'primary_secondary', 'x12_270_271'],
    encounters: ['oa_23_hydra'],
    cases: ['case_hydra_okwu'],
    npcsActive: ['kim', 'alex'],
  },
  {
    id: 10,
    title: 'The Audit',
    subtitle: 'Everything you did is under review.',
    hospitalDescription: 'The conference room. Auditors have arrived.',
    waitingRoomDescription: 'A room of mirrors. Every shortcut reflects back at you.',
    concepts: ['audit', 'compliance', 'upcoding', 'documentation'],
    encounters: ['boss_audit'],
    cases: ['case_audit_finale'],
    npcsActive: ['dana', 'martinez', 'pat', 'sam', 'auditor_carl', 'auditor_chen', 'auditor_rivera', 'auditor_eddi'],
    bossEncounter: 'boss_audit',
  },
]
