// Canonical {textureKey: spriteSlot} mapping. EMPTY by design —
// the game is back to fully-procedural object rendering. Every
// hospital object texture is generated at runtime in BootScene
// (the 12 detailed procedurals in `makeHospitalTiles`, plus the
// generic tinted-box fallbacks below).
//
// To bring back PNG-backed art for any single key, add an entry
// here mapping `texture_key → 'slot_filename'` (without the
// `.png`) and drop the cell into public/sprites/objects-raw/. The
// procedural fallback steps aside via a `if (!textures.exists(...))`
// guard so PNG always wins when present.

export const OBJECT_SOURCES: Record<string, string> = {}

/**
 * All hospital object texture keys with a (procedural-era) fallback
 * fill color. Used by:
 *   - `BootScene.ensureFallbackObjectTextures` to generate simple
 *     tinted-box procedurals for any key that doesn't already have
 *     a detailed `makeHospitalTiles` draw.
 *   - The map editor (via `src/map-editor/data.ts`) to render every
 *     placed object as a tinted CSS box, since there are no PNGs
 *     to load.
 *
 * Two tiers:
 *   1. The 12 keys with detailed procedurals in BootScene — color
 *      matches their dominant pixel fill so the editor's box
 *      visually approximates the in-game art.
 *   2. The "orphan" keys (Phase-C content props that never had
 *      detailed art) — each a distinct color so the editor can
 *      tell them apart.
 */
export const OBJECT_FALLBACK_COLORS: Record<string, number> = {
  // Detailed procs (already drawn in makeHospitalTiles)
  h_desk:       0x5a4a3a, // wood
  h_chair:      0x3a3a4a, // dark slate
  h_equipment:  0x6a6a8a, // pale blue-grey monitor
  h_plant:      0x4a6a4a, // potted-fern green
  h_water:      0xa0c4d4, // pale blue
  h_cabinet:    0x6a4a3a, // wood
  h_whiteboard: 0xb8b8b8, // off-white board
  h_counter:    0x5a5a6a, // counter slate
  h_vending:    0xa05050, // red vending
  h_bulletin:   0xa07a4a, // cork brown
  h_bed:        0xc8c8d0, // pale linen
  h_fax:        0x8a8a4a, // beige

  // Orphan procs — generic tinted boxes generated by the fallback
  h_aed:        0xc4505a, // safety red
  h_sanitizer:  0xb0c4d4, // medical pale blue
  h_couch:      0x6a7a9a, // muted blue couch
  h_bench:      0x4a7a4a, // green bench
  h_brochure:   0xa07a4a, // wood rack
  h_signin:     0x8a8a4a, // clipboard tan
  h_payphone:   0x4a4a4a, // dark plastic
  h_arrow_sign: 0x6a7a8a, // signage blue
  h_trash:      0x5a5a6a, // dark grey bin
  h_iv_stand:   0xa0c4d4, // chrome + saline
  h_wheelchair: 0x4a6a8a, // navy chair
  h_gurney:     0x4a6a8a, // navy + chrome
  h_bookshelf:  0x6a4a3a, // dark wood
  h_shredder:   0x4a4a4a, // dark plastic
  h_kiosk:      0x6a7a8a, // grey kiosk
  h_directory:  0x6a7a8a, // signage panel
  h_pneumatic:  0x6a6a8a, // tube grey
  h_elevator:   0x8a8a8a, // metal doors
  h_fountain:   0x6a8a9a, // chrome + water
  h_wet_floor:  0xf0c868, // safety yellow
  h_mop_bucket: 0xa0a068, // olive bucket
}
